
services:
  # =============================================================================
  # NGINX - Reverse Proxy e Servidor Web
  # =============================================================================
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME:-controleobras}-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      php:
        condition: service_healthy
    networks:
      - app-network
    command: ["/entrypoint.sh", "nginx", "-g", "daemon off;"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # =============================================================================
  # PHP-FPM - Aplicação Laravel
  # =============================================================================
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - APP_ENV=${APP_ENV:-production}
    image: ${APP_NAME:-controleobras}-app:latest
    container_name: ${APP_NAME:-controleobras}-php
    restart: always
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=app
      - APP_ENV=${APP_ENV:-production}
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap:/var/www/bootstrap/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep '[p]hp-fpm' | head -1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # =============================================================================
  # WEBSOCKET - Laravel Reverb
  # =============================================================================
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - APP_ENV=${APP_ENV:-production}
    image: ${APP_NAME:-controleobras}-websocket:latest
    container_name: ${APP_NAME:-controleobras}-websocket
    restart: always
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=websocket
      - APP_ENV=${APP_ENV:-production}
    ports:
      - "6001:6001"
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap:/var/www/bootstrap/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      php:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "netcat", "-z", "localhost", "6001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # =============================================================================
  # QUEUE WORKER - Processamento de Filas
  # =============================================================================
  queue:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - APP_ENV=${APP_ENV:-production}
    image: ${APP_NAME:-controleobras}-queue:latest
    container_name: ${APP_NAME:-controleobras}-queue
    restart: always
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=queue
      - QUEUE_NAMES=pdf,default
      - APP_ENV=${APP_ENV:-production}
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap:/var/www/bootstrap/cache
      - ./queue-logs:/var/www/storage/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      php:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "queue:work"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # =============================================================================
  # SCHEDULER - Laravel Cron Jobs
  # =============================================================================
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - APP_ENV=${APP_ENV:-production}
    image: ${APP_NAME:-controleobras}-scheduler:latest
    container_name: ${APP_NAME:-controleobras}-scheduler
    restart: always
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=scheduler
      - APP_ENV=${APP_ENV:-production}
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap:/var/www/bootstrap/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      php:
        condition: service_healthy
    networks:
      - app-network

  # =============================================================================
  # MYSQL DATABASE
  # =============================================================================
  db:
    image: mysql:8.0
    container_name: ${APP_NAME:-controleobras}-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --innodb-buffer-pool-size=256M
      --max-connections=100
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # =============================================================================
  # REDIS - Cache e Sessões
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME:-controleobras}-redis
    restart: always
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: ["redis-server", "--requirepass", "secret", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "secret", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# =============================================================================
# VOLUMES - Dados Persistentes
# =============================================================================
volumes:
  db_data:
  redis_data:
  app_storage:
  app_bootstrap:

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  app-network:
    driver: bridge
